/* <auto-generated> by Tools/gen_quest_zones.py — DO NOT EDIT. */
#ifndef D2ARCH_QUESTZONES_G_H
#define D2ARCH_QUESTZONES_G_H

typedef struct { short quest; short zone; } QuestZoneEntry;

static const QuestZoneEntry g_questZones[] = {
    {    1,    8 },   /* Act 1 - Cave 1 */
    {    2,   17 },   /* Act 1 - Graveyard */
    {    3,   28 },   /* Act 1 - Barracks */
    {    4,    5 },   /* Act 1 - Wilderness 4 */
    {    5,   25 },   /* Act 1 - Crypt 3 E */
    {    6,   37 },   /* Act 1 - Catacombs 4 */
    {    7,    8 },   /* Act 1 - Cave 1 */
    {    8,    3 },   /* Act 1 - Wilderness 2 */
    {    9,   18 },   /* Act 1 - Crypt 1 A */
    {   10,    2 },   /* Act 1 - Wilderness 1 */
    {   11,    3 },   /* Act 1 - Wilderness 2 */
    {   12,    4 },   /* Act 1 - Wilderness 3 */
    {   13,    5 },   /* Act 1 - Wilderness 4 */
    {   14,    6 },   /* Act 1 - Wilderness 5 */
    {   15,    7 },   /* Act 1 - Wilderness 6 */
    {   16,    8 },   /* Act 1 - Cave 1 */
    {   17,    9 },   /* Act 1 - Cave 2 */
    {   18,   10 },   /* Act 1 - Cave 3 */
    {   19,   17 },   /* Act 1 - Graveyard */
    {   20,   18 },   /* Act 1 - Crypt 1 A */
    {   21,   19 },   /* Act 1 - Crypt 2 A */
    {   22,   22 },   /* Act 1 - Crypt 3 B */
    {   23,   23 },   /* Act 1 - Crypt 3 C */
    {   24,   24 },   /* Act 1 - Crypt 3 D */
    {   25,   25 },   /* Act 1 - Crypt 3 E */
    {   26,   26 },   /* Act 1 - Monastery */
    {   27,   26 },   /* Act 1 - Monastery */
    {   28,   28 },   /* Act 1 - Barracks */
    {   29,   29 },   /* Act 1 - Jail 1 */
    {   30,   30 },   /* Act 1 - Jail 2 */
    {   31,   31 },   /* Act 1 - Jail 3 */
    {   32,   32 },   /* Act 1 - Courtyard 2 */
    {   33,   33 },   /* Act 1 - Cathedral */
    {   34,   34 },   /* Act 1 - Catacombs 1 */
    {   35,   35 },   /* Act 1 - Catacombs 2 */
    {   36,   36 },   /* Act 1 - Catacombs 3 */
    {   37,   38 },   /* Act 1 - Tristram */
    {   38,   13 },   /* Act 1 - Cave 2 Treasure */
    {   39,   14 },   /* Act 1 - Cave 3 Treasure */
    {   40,    2 },   /* Act 1 - Wilderness 1 */
    {   41,    3 },   /* Act 1 - Wilderness 2 */
    {   42,    4 },   /* Act 1 - Wilderness 3 */
    {   43,    5 },   /* Act 1 - Wilderness 4 */
    {   44,    6 },   /* Act 1 - Wilderness 5 */
    {   45,    7 },   /* Act 1 - Wilderness 6 */
    {   46,    8 },   /* Act 1 - Cave 1 */
    {   47,   38 },   /* Act 1 - Tristram */
    {   48,   34 },   /* Act 1 - Catacombs 1 */
    {   49,   21 },   /* Act 1 - Crypt 3 A */
    {   50,    3 },   /* Act 1 - Wilderness 2 */
    {   51,    4 },   /* Act 1 - Wilderness 3 */
    {   52,    5 },   /* Act 1 - Wilderness 4 */
    {   53,    6 },   /* Act 1 - Wilderness 5 */
    {   54,   27 },   /* Act 1 - Courtyard 1 */
    {   55,   30 },   /* Act 1 - Jail 2 */
    {   56,   28 },   /* Act 1 - Barracks */
    {   57,   35 },   /* Act 1 - Catacombs 2 */
    {   58,   12 },   /* Act 1 - Cave 5 */
    {   59,   11 },   /* Act 1 - Cave 4 */
    {   60,   12 },   /* Act 1 - Cave 5 */
    {   61,   16 },   /* Act 1 - Cave 5 Treasure */
    {   62,   32 },   /* Act 1 - Courtyard 2 */
    {   63,   37 },   /* Act 1 - Catacombs 4 */
    {   70,    9 },   /* Act 1 - Cave 2 */
    {   71,    4 },   /* Act 1 - Wilderness 3 */
    {   72,    5 },   /* Act 1 - Wilderness 4 */
    {   73,   38 },   /* Act 1 - Tristram */
    {   74,   25 },   /* Act 1 - Crypt 3 E */
    {   75,   30 },   /* Act 1 - Jail 2 */
    {   77,   33 },   /* Act 1 - Cathedral */
    {   80,   28 },   /* Act 1 - Barracks */
    {  101,   49 },   /* Act 2 - Sewer 1 C */
    {  102,   60 },   /* Act 2 - Tomb 2 Treasure */
    {  103,   61 },   /* Act 2 - Tomb 3 Treasure */
    {  104,   74 },   /* Act 2 - Arcane */
    {  105,   74 },   /* Act 2 - Arcane */
    {  106,   73 },   /* Act 2 - Duriel's Lair */
    {  110,   41 },   /* Act 2 - Desert 1 */
    {  111,   42 },   /* Act 2 - Desert 2 */
    {  112,   43 },   /* Act 2 - Desert 3 */
    {  113,   44 },   /* Act 2 - Desert 4 */
    {  114,   45 },   /* Act 2 - Desert 5 */
    {  115,   47 },   /* Act 2 - Sewer 1 A */
    {  116,   48 },   /* Act 2 - Sewer 1 B */
    {  117,   56 },   /* Act 2 - Tomb 2 A */
    {  118,   57 },   /* Act 2 - Tomb 2 B */
    {  119,   60 },   /* Act 2 - Tomb 2 Treasure */
    {  120,   62 },   /* Act 2 - Lair 1 A */
    {  121,   63 },   /* Act 2 - Lair 1 B */
    {  122,   64 },   /* Act 2 - Lair 1 Treasure */
    {  123,   65 },   /* Act 2 - Sewer 2 A */
    {  124,   74 },   /* Act 2 - Arcane */
    {  125,   52 },   /* Act 2 - Basement 1 */
    {  126,   53 },   /* Act 2 - Basement 2 */
    {  127,   54 },   /* Act 2 - Basement 3 */
    {  128,   46 },   /* Act 2 - Valley of the Kings */
    {  129,   55 },   /* Act 2 - Tomb 1 A */
    {  130,   49 },   /* Act 2 - Sewer 1 C */
    {  131,   51 },   /* Act 2 - Corrupt Harem 1 */
    {  132,   58 },   /* Act 2 - Tomb 3 A */
    {  133,   61 },   /* Act 2 - Tomb 3 Treasure */
    {  134,   59 },   /* Act 2 - Tomb 1 Treasure */
    {  135,   66 },   /* Act 2 - Tomb Tal 1 */
    {  136,   67 },   /* Act 2 - Tomb Tal 2 */
    {  137,   68 },   /* Act 2 - Tomb Tal 3 */
    {  138,   69 },   /* Act 2 - Tomb Tal 4 */
    {  139,   70 },   /* Act 2 - Tomb Tal 5 */
    {  140,   41 },   /* Act 2 - Desert 1 */
    {  141,   42 },   /* Act 2 - Desert 2 */
    {  142,   43 },   /* Act 2 - Desert 3 */
    {  143,   44 },   /* Act 2 - Desert 4 */
    {  144,   74 },   /* Act 2 - Arcane */
    {  145,   71 },   /* Act 2 - Tomb Tal 6 */
    {  146,   72 },   /* Act 2 - Tomb Tal 7 */
    {  150,   48 },   /* Act 2 - Sewer 1 B */
    {  151,   42 },   /* Act 2 - Desert 2 */
    {  152,   57 },   /* Act 2 - Tomb 2 B */
    {  153,   43 },   /* Act 2 - Desert 3 */
    {  154,   44 },   /* Act 2 - Desert 4 */
    {  155,   52 },   /* Act 2 - Basement 1 */
    {  156,   74 },   /* Act 2 - Arcane */
    {  157,   46 },   /* Act 2 - Valley of the Kings */
    {  170,   49 },   /* Act 2 - Sewer 1 C */
    {  171,   42 },   /* Act 2 - Desert 2 */
    {  172,   61 },   /* Act 2 - Tomb 3 Treasure */
    {  173,   43 },   /* Act 2 - Desert 3 */
    {  174,   52 },   /* Act 2 - Basement 1 */
    {  175,   64 },   /* Act 2 - Lair 1 Treasure */
    {  176,   44 },   /* Act 2 - Desert 4 */
    {  177,   44 },   /* Act 2 - Desert 4 */
    {  178,   74 },   /* Act 2 - Arcane */
    {  179,   46 },   /* Act 2 - Valley of the Kings */
    {  201,   95 },   /* Act 3 - Temple 2 */
    {  202,   83 },   /* Act 3 - Travincal */
    {  203,   83 },   /* Act 3 - Travincal */
    {  204,   80 },   /* Act 3 - Kurast 2 */
    {  205,   83 },   /* Act 3 - Travincal */
    {  206,  102 },   /* Act 3 - Mephisto 3 */
    {  210,   76 },   /* Act 3 - Jungle 1 */
    {  211,   77 },   /* Act 3 - Jungle 2 */
    {  212,   78 },   /* Act 3 - Jungle 3 */
    {  213,   79 },   /* Act 3 - Kurast 1 */
    {  214,   80 },   /* Act 3 - Kurast 2 */
    {  215,   81 },   /* Act 3 - Kurast 3 */
    {  216,   83 },   /* Act 3 - Travincal */
    {  217,   84 },   /* Act 3 - Spider 1 */
    {  218,   88 },   /* Act 3 - Dungeon 2 A */
    {  219,   89 },   /* Act 3 - Dungeon 2 B */
    {  220,   92 },   /* Act 3 - Sewer 1 */
    {  221,   93 },   /* Act 3 - Sewer 2 */
    {  222,  100 },   /* Act 3 - Mephisto 1 */
    {  223,  101 },   /* Act 3 - Mephisto 2 */
    {  224,   82 },   /* Act 3 - Kurast 4 */
    {  230,   85 },   /* Act 3 - Spider 2 */
    {  231,   86 },   /* Act 3 - Dungeon 1 A */
    {  232,   87 },   /* Act 3 - Dungeon 1 B */
    {  233,   90 },   /* Act 3 - Dungeon 1 Treasure */
    {  234,   91 },   /* Act 3 - Dungeon 2 Treasure */
    {  235,   94 },   /* Act 3 - Temple 1 */
    {  236,   95 },   /* Act 3 - Temple 2 */
    {  237,   96 },   /* Act 3 - Temple 3 */
    {  238,   97 },   /* Act 3 - Temple 4 */
    {  239,   98 },   /* Act 3 - Temple 5 */
    {  240,   76 },   /* Act 3 - Jungle 1 */
    {  241,   78 },   /* Act 3 - Jungle 3 */
    {  242,   80 },   /* Act 3 - Kurast 2 */
    {  243,   83 },   /* Act 3 - Travincal */
    {  244,  100 },   /* Act 3 - Mephisto 1 */
    {  245,   99 },   /* Act 3 - Temple 6 */
    {  250,   76 },   /* Act 3 - Jungle 1 */
    {  251,   77 },   /* Act 3 - Jungle 2 */
    {  252,   78 },   /* Act 3 - Jungle 3 */
    {  253,   79 },   /* Act 3 - Kurast 1 */
    {  254,   80 },   /* Act 3 - Kurast 2 */
    {  255,   81 },   /* Act 3 - Kurast 3 */
    {  256,   83 },   /* Act 3 - Travincal */
    {  257,  101 },   /* Act 3 - Mephisto 2 */
    {  271,   84 },   /* Act 3 - Spider 1 */
    {  272,   88 },   /* Act 3 - Dungeon 2 A */
    {  273,   79 },   /* Act 3 - Kurast 1 */
    {  274,   94 },   /* Act 3 - Temple 1 */
    {  275,   92 },   /* Act 3 - Sewer 1 */
    {  276,   83 },   /* Act 3 - Travincal */
    {  277,   83 },   /* Act 3 - Travincal */
    {  278,   83 },   /* Act 3 - Travincal */
    {  279,  100 },   /* Act 3 - Mephisto 1 */
    {  280,  101 },   /* Act 3 - Mephisto 2 */
    {  281,  101 },   /* Act 3 - Mephisto 2 */
    {  301,  105 },   /* Act 4 - Mesa 2 */
    {  302,  107 },   /* Act 4 - Lava 1 */
    {  303,  108 },   /* Act 4 - Diablo 1 */
    {  310,  104 },   /* Act 4 - Mesa 1 */
    {  311,  105 },   /* Act 4 - Mesa 2 */
    {  312,  106 },   /* Act 4 - Mesa 3 */
    {  313,  107 },   /* Act 4 - Lava 1 */
    {  314,  108 },   /* Act 4 - Diablo 1 */
    {  340,  104 },   /* Act 4 - Mesa 1 */
    {  341,  105 },   /* Act 4 - Mesa 2 */
    {  342,  106 },   /* Act 4 - Mesa 3 */
    {  343,  107 },   /* Act 4 - Lava 1 */
    {  344,  108 },   /* Act 4 - Diablo 1 */
    {  350,  106 },   /* Act 4 - Mesa 3 */
    {  351,  107 },   /* Act 4 - Lava 1 */
    {  370,  104 },   /* Act 4 - Mesa 1 */
    {  371,  105 },   /* Act 4 - Mesa 2 */
    {  372,  106 },   /* Act 4 - Mesa 3 */
    {  373,  107 },   /* Act 4 - Lava 1 */
    {  374,  108 },   /* Act 4 - Diablo 1 */
    {  375,  108 },   /* Act 4 - Diablo 1 */
    {  376,  108 },   /* Act 4 - Diablo 1 */
    {  401,  110 },   /* Act 5 - Siege 1 */
    {  402,  112 },   /* Act 5 - Barricade 2 */
    {  403,  113 },   /* Act 5 - Ice Cave 1 */
    {  404,  124 },   /* Act 5 - Temple Boss */
    {  405,  120 },   /* Act 5 - Mountain Top */
    {  406,  132 },   /* Act 5 - World Stone */
    {  410,  110 },   /* Act 5 - Siege 1 */
    {  411,  111 },   /* Act 5 - Barricade 1 */
    {  412,  112 },   /* Act 5 - Barricade 2 */
    {  413,  113 },   /* Act 5 - Ice Cave 1 */
    {  414,  118 },   /* Act 5 - Ice Cave 3 */
    {  415,  119 },   /* Act 5 - Ice Cave 3A */
    {  416,  117 },   /* Act 5 - Barricade Snow */
    {  417,  122 },   /* Act 5 - Temple 1 */
    {  418,  123 },   /* Act 5 - Temple 2 */
    {  419,  124 },   /* Act 5 - Temple Boss */
    {  420,  128 },   /* Act 5 - Baal Temple 1 */
    {  421,  129 },   /* Act 5 - Baal Temple 2 */
    {  422,  130 },   /* Act 5 - Baal Temple 3 */
    {  423,  131 },   /* Act 5 - Throne Room */
    {  430,  114 },   /* Act 5 - Ice Cave 1A */
    {  431,  115 },   /* Act 5 - Ice Cave 2 */
    {  432,  116 },   /* Act 5 - Ice Cave 2A */
    {  433,  125 },   /* Act 5 - Hell 1 */
    {  434,  126 },   /* Act 5 - Hell 2 */
    {  435,  127 },   /* Act 5 - Hell 3 */
    {  440,  110 },   /* Act 5 - Siege 1 */
    {  441,  111 },   /* Act 5 - Barricade 1 */
    {  442,  112 },   /* Act 5 - Barricade 2 */
    {  443,  113 },   /* Act 5 - Ice Cave 1 */
    {  444,  128 },   /* Act 5 - Baal Temple 1 */
    {  450,  111 },   /* Act 5 - Barricade 1 */
    {  451,  112 },   /* Act 5 - Barricade 2 */
    {  452,  113 },   /* Act 5 - Ice Cave 1 */
    {  454,  123 },   /* Act 5 - Temple 2 */
    {  455,  115 },   /* Act 5 - Ice Cave 2 */
    {  456,  117 },   /* Act 5 - Barricade Snow */
    {  457,  129 },   /* Act 5 - Baal Temple 2 */
    {  470,  110 },   /* Act 5 - Siege 1 */
    {  471,  111 },   /* Act 5 - Barricade 1 */
    {  472,  112 },   /* Act 5 - Barricade 2 */
    {  473,  118 },   /* Act 5 - Ice Cave 3 */
    {  474,  119 },   /* Act 5 - Ice Cave 3A */
    {  475,  121 },   /* Act 5 - Temple Entrance */
    {  476,  115 },   /* Act 5 - Ice Cave 2 */
    {  477,  129 },   /* Act 5 - Baal Temple 2 */
};
#define QUESTZONE_COUNT 256

/* Area this quest happens in, or -1. */
static int QuestZone_For(int questId) {
    for (int i = 0; i < QUESTZONE_COUNT; i++)
        if (g_questZones[i].quest == questId) return g_questZones[i].zone;
    return -1;
}

#endif
